// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY1jfNqU7ReG4yMr4UySlSXWMyFNvwUcY',
    appId: '1:999215647977:web:03b958b5aa768a5eacf478',
    messagingSenderId: '999215647977',
    projectId: 'jops-28d49',
    authDomain: 'jops-28d49.firebaseapp.com',
    storageBucket: 'jops-28d49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2bcwkzkmho306yhm_mQWvtkWXEZ91_Y',
    appId: '1:999215647977:android:03dddded7ea1c9cbacf478',
    messagingSenderId: '999215647977',
    projectId: 'jops-28d49',
    storageBucket: 'jops-28d49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgzTBb2zoDCrje0DKAJkTXLU7naak3XyM',
    appId: '1:999215647977:ios:18ebe9c3498da641acf478',
    messagingSenderId: '999215647977',
    projectId: 'jops-28d49',
    storageBucket: 'jops-28d49.appspot.com',
    iosBundleId: 'com.example.untitled10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgzTBb2zoDCrje0DKAJkTXLU7naak3XyM',
    appId: '1:999215647977:ios:473cc9f494dcfb75acf478',
    messagingSenderId: '999215647977',
    projectId: 'jops-28d49',
    storageBucket: 'jops-28d49.appspot.com',
    iosBundleId: 'com.example.untitled10.RunnerTests',
  );
}
